TASK:
    NAME: 'UNIFORMITY'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk' # Testing this
    OBJECTIVES: ['autoencode'] # apparently not relevant (and next step doesn't seem much worse)
    HIDDEN_SIZE: 128
    PROPRIOCEPTION_DELTA: True
    # NOISED_SIGNAL: True # TODO
TRAIN:
    EPOCHS: 30