TASK:
    NAME: 'snakes'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch', 'adversarial_patch']
    NOISED_SIGNAL: True
    FOURIER_PROPRIO: True
    HIDDEN_SIZE: 512
    WALK_PACE: 0.0
    ADV_CONF: 0.2
TRAIN:
    EPOCHS: 12