TASK:
    NAME: 'troxler'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: True
    FOURIER_PROPRIO: True
    HIDDEN_SIZE: 512
    SACCADE_BATCH: 64
TRAIN:
    EPOCHS: 120